# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "nvme_resources"
edition.workspace = true
rust-version.workspace = true

[dependencies]
vm_resource.workspace = true
nvme_spec.workspace = true
async-trait.workspace = true

mesh.workspace = true

guid = { workspace = true, features = ["mesh"] }

[lints]
workspace = true
